package com.robertomartus.progresstracker.data;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.robertomartus.progresstracker.data.WorkAsAmountGreenDaoImpl;

import com.robertomartus.progresstracker.data.WorkAsAmountGreenDaoImplDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig workAsAmountGreenDaoImplDaoConfig;

    private final WorkAsAmountGreenDaoImplDao workAsAmountGreenDaoImplDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        workAsAmountGreenDaoImplDaoConfig = daoConfigMap.get(WorkAsAmountGreenDaoImplDao.class).clone();
        workAsAmountGreenDaoImplDaoConfig.initIdentityScope(type);

        workAsAmountGreenDaoImplDao = new WorkAsAmountGreenDaoImplDao(workAsAmountGreenDaoImplDaoConfig, this);

        registerDao(WorkAsAmountGreenDaoImpl.class, workAsAmountGreenDaoImplDao);
    }
    
    public void clear() {
        workAsAmountGreenDaoImplDaoConfig.getIdentityScope().clear();
    }

    public WorkAsAmountGreenDaoImplDao getWorkAsAmountGreenDaoImplDao() {
        return workAsAmountGreenDaoImplDao;
    }

}
