package com.robertomartus.progresstracker.data;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.robertomartus.progresstracker.data.WorkAsAmount;

import com.robertomartus.progresstracker.data.WorkAsAmountDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig workAsAmountDaoConfig;

    private final WorkAsAmountDao workAsAmountDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        workAsAmountDaoConfig = daoConfigMap.get(WorkAsAmountDao.class).clone();
        workAsAmountDaoConfig.initIdentityScope(type);

        workAsAmountDao = new WorkAsAmountDao(workAsAmountDaoConfig, this);

        registerDao(WorkAsAmount.class, workAsAmountDao);
    }
    
    public void clear() {
        workAsAmountDaoConfig.getIdentityScope().clear();
    }

    public WorkAsAmountDao getWorkAsAmountDao() {
        return workAsAmountDao;
    }

}
