package com.robertomartus.progresstracker.data;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.robertomartus.progresstracker.data.ProgressableItem;

import com.robertomartus.progresstracker.data.ProgressableItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig progressableItemDaoConfig;

    private final ProgressableItemDao progressableItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        progressableItemDaoConfig = daoConfigMap.get(ProgressableItemDao.class).clone();
        progressableItemDaoConfig.initIdentityScope(type);

        progressableItemDao = new ProgressableItemDao(progressableItemDaoConfig, this);

        registerDao(ProgressableItem.class, progressableItemDao);
    }
    
    public void clear() {
        progressableItemDaoConfig.getIdentityScope().clear();
    }

    public ProgressableItemDao getProgressableItemDao() {
        return progressableItemDao;
    }

}
