package com.robertomartus.progresstracker.data;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.robertomartus.progresstracker.data.WorkAsAmountGreenDaoImpl;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table WORK_AS_AMOUNT_GREEN_DAO_IMPL.
*/
public class WorkAsAmountGreenDaoImplDao extends AbstractDao<WorkAsAmountGreenDaoImpl, Long> {

    public static final String TABLENAME = "WORK_AS_AMOUNT_GREEN_DAO_IMPL";

    /**
     * Properties of entity WorkAsAmountGreenDaoImpl.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Done = new Property(1, Long.class, "done", false, "DONE");
        public final static Property Total = new Property(2, Long.class, "total", false, "TOTAL");
    };


    public WorkAsAmountGreenDaoImplDao(DaoConfig config) {
        super(config);
    }
    
    public WorkAsAmountGreenDaoImplDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'WORK_AS_AMOUNT_GREEN_DAO_IMPL' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'DONE' INTEGER," + // 1: done
                "'TOTAL' INTEGER);"); // 2: total
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'WORK_AS_AMOUNT_GREEN_DAO_IMPL'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, WorkAsAmountGreenDaoImpl entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long done = entity.getDone();
        if (done != null) {
            stmt.bindLong(2, done);
        }
 
        Long total = entity.getTotal();
        if (total != null) {
            stmt.bindLong(3, total);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public WorkAsAmountGreenDaoImpl readEntity(Cursor cursor, int offset) {
        WorkAsAmountGreenDaoImpl entity = new WorkAsAmountGreenDaoImpl( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // done
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // total
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, WorkAsAmountGreenDaoImpl entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDone(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setTotal(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(WorkAsAmountGreenDaoImpl entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(WorkAsAmountGreenDaoImpl entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
