package com.robertomartus.progresstracker.data;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;

/**
 * Entity mapped to table WORK_AS_AMOUNT.
 */
public class WorkAsAmount implements com.robertomartus.progresstracker.data.Work {

    private Long id;
    private Long amount;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public WorkAsAmount() {
    }

    public WorkAsAmount(Long id) {
        this.id = id;
    }

    public WorkAsAmount(Long id, Long amount) {
        this.id = id;
        this.amount = amount;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAmount() {
        return amount;
    }

    public void setAmount(Long amount) {
        this.amount = amount;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof WorkAsAmount)) {
            return false;
        }
        WorkAsAmount other = (WorkAsAmount) obj;
        return Objects.equal(id, other.id) && Objects.equal(amount, other.amount);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(id, amount);
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
                .add("id", id)
                .add("amount", amount)
                .toString();
    }
    // KEEP METHODS END

}
